# This is a basic workflow to help you get started with Actions

name: Docker Actions

on:
  push:
    branches: [ side ]

jobs:
  action:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: hello-action
        uses: ./

